net-p2p/syncthing::pg_overlay
dev-libs/boost::pg_overlay
www-client/firefox::pg_overlay
www-client/firefox-l10n::pg_overlay 
sys-apps/bleachbit::pg_overlay
dev-python/dasbus::wayland-desktop
net-libs/nodejs::pg_overlay
dev-libs/libevent::pg_overlay
net-misc/openssh::pg_overlay

