#!/bin/sh

PORTDIR=$(portageq get_repo_path / gentoo)

chown -R portage:portage ${PORTDIR}
chown -R portage:portage /usr/local/share/portage/

chown -R portage:portage /com/lib/portage
find /com/lib/portage/packages/ -type f -exec chmod 644 "{}" \;
find /com/lib/portage/packages/ -type d -exec chmod 755 "{}" \;

