#!/bin/sh

su - portage -s /bin/bash -c '(cd /usr/local/share/portage/local; ./push compress)'
su - portage -s /bin/bash -c '(cd /usr/local/share/portage/profiles; ./push compress)'
su - portage -s /bin/bash -c '(cd /usr/portage; git stash; git clean -d -f; git fsck; git gc --aggressive --prune=now)'

su - portage -s /bin/bash -c '(cd /usr/portage/local/layman; ./pull_all compress)'
