#!/bin/bash

# git checkout master
git pull

## Clean
find . -name "*~" -delete

# Push
git add -A .
git commit -am "$(date)"
git push
# git push git@github.com:yamadharma/karma-profiles.git

# Mirror
# git push --mirror git@github.com:yamadharma/karma-profiles.git
# git push --mirror git@bitbucket.org:yamadharma/soft-gentoo-portage-profiles.git

# git compress
if [[ $1 == "compress" ]]
then
    if [[ -d .git ]]
    then
	git fsck
	git gc --prune=now
	git gc --aggressive --prune=now
    fi
fi
