#!/bin/sh

PORTDIR=$(portageq get_repo_path / gentoo)

(cd /usr/local/share/portage/local; ./push)
(cd /usr/local/share/portage/profiles; ./push)
(cd ${PORTDIR}; git stash; git clean -d -f; git pull)

chown -R portage:portage ${PORTDIR}
chown -R portage:portage /usr/local/share/portage/

# /usr/sbin/emaint sync -a

su - portage -s /bin/bash -c 'emerge --sync'

layman -f
su - portage -s /bin/bash -c 'layman -S'
#layman -a ALL

eix-update

cfg-update --optimize-backups

