#!/bin/bash

RSYNC_MIRROR=rsync://mirrors.mi.ras.ru/CTAN/

mkdir -p /com/lib/portage/extras/texlive

rsync -rltpD -v -HS --delete ${RSYNC_MIRROR}/systems/texlive/tlnet/ /com/lib/portage/extras/texlive
