#!/bin/sh

systemctl enable rpcbind.service
systemctl enable sshd.service
systemctl enable autofs.service
systemctl enable rsyslog.service
systemctl enable cups.service
systemctl enable gpm.service
systemctl enable NetworkManager.service
systemctl enable kdm.service
