#!/bin/sh

DIR=$(dirname $(dirname $(dirname $(readlink -f $0))))
echo ${DIR}

cd /etc
ln -snf /etc/make.profile/make.conf .

mkdir -p /etc/portage
cd /etc/portage
rm -rf /etc/portage/package.keywords
ln -snf ${DIR}/portage/* .

ln -snf /var/db/repos/karma-profiles/host/$(hostnamectl hostname) /etc/portage/make.profile 

