#!/bin/sh


(cd /usr/local/share/portage/local; ./push)
(cd /usr/local/share/portage/profiles; ./push)
(cd /usr/portage; git stash; git clean -d -f)

chown -R portage:portage /usr/portage/
chown -R portage:portage /usr/local/share/portage/

emaint sync -a

#layman -f
layman -S
#layman -a ALL

eix-update

cfg-update --optimize-backups

