sys-kernel/installkernel
sys-kernel/installkernel-systemd
sys-kernel/dracut

=sys-kernel/gentoo-sources-6.1*
=sys-kernel/linux-headers-6.1*
=sys-kernel/gentoo-kernel-bin-6.1*
=sys-kernel/gentoo-kernel-bin-6.6*
=sys-kernel/linux-headers-6.6*
=sys-kernel/gentoo-sources-6.6*
=sys-kernel/gentoo-kernel-bin-6.12*
=sys-kernel/linux-headers-6.12*
=sys-kernel/gentoo-sources-6.12*
=sys-kernel/pf-sources-6.12*
=virtual/dist-kernel-6.18*
=sys-kernel/gentoo-kernel-bin-6.18*
=sys-kernel/gentoo-kernel-6.18*
=sys-kernel/linux-headers-6.18*
=sys-kernel/gentoo-sources-6.18*
=sys-kernel/pf-sources-6.18*
=virtual/dist-kernel-7.1*
=sys-kernel/gentoo-kernel-bin-7.1*
=sys-kernel/gentoo-kernel-7.1*
=sys-kernel/linux-headers-7.1*
=sys-kernel/gentoo-sources-7.1*
=sys-kernel/pf-sources-7.1*
#=virtual/dist-kernel-7.2*
#=sys-kernel/gentoo-kernel-bin-7.2*
#=sys-kernel/gentoo-kernel-7.2*
#=sys-kernel/linux-headers-7.2*
#=sys-kernel/gentoo-sources-7.2*
#=sys-kernel/pf-sources-7.2*


