#!/bin/bash

# Сжатие git
git_compress () {

    CUR_DIR=$(pwd)

    if [[ -d .git ]]
    then
	echo -e "Compressing \033[1m""${CUR_DIR}"; tput sgr0
	
	su portage -s /bin/bash -p \
	   -c '\
	      git fsck;\
	      git gc --prune=now;\
	      git gc --aggressive --prune=now'
    fi
}

git_compress_sub () {
    
    for i in *
    do
	if [[ -d $i ]]
	then
	    cd "$i"
	    
	    if [[ -d .git ]]
	    then
		echo -e "\033[1m""Compressing $i"; tput sgr0

		su portage \
		   -s /bin/bash -p \
		   -c '\
		   git fsck;\
		   git gc --prune=now;\
		   git gc --aggressive --prune=now'
	    fi
	    
	    cd ../
	fi
    done
}

for i in $(portageq get_repos /)
do
    chown -R portage:portage $(portageq get_repo_path / ${i})
    pushd $(portageq get_repo_path / ${i})
    git_compress
    popd
done
