#!/bin/bash

LAYMAN_DIR="$(portageq envvar LAYMAN_DIR)"

# Сжатие git
git_compress () {

    CUR_DIR=$(pwd)
    
    if [[ -d .git ]]
    then
	echo -e "\033[1m""Compressing ${CUR_DIR}"; tput sgr0
	
	su - portage -s /bin/bash -p \
	   -c '\
	      git fsck;\
	      git gc --prune=now;\
	      git gc --aggressive --prune=now'
    fi
}

git_compress_sub () {
    
    for i in *
    do
	if [[ -d $i ]]
	then
	    cd "$i"
	    
	    if [[ -d .git ]]
	    then
		echo -e "\033[1m""Compressing $i"; tput sgr0

		su - portage \
		   -s /bin/bash -p \
		   -c '\
		   git fsck;\
		   git gc --prune=now;\
		   git gc --aggressive --prune=now'
	    fi
	    
	    cd ../
	fi
    done
}

(cd /usr/local/share/portage/local; git_compress)
(cd /usr/local/share/portage/profiles; git_compress)
(cd /usr/portage; git_compress)

(cd ${LAYMAN_DIR}; git_compress_sub)

