# bashrc
# This file created by 
export CHOST="x86_64-pc-linux-gnu"
export CFLAGS="-march=athlon64 -mtune=athlon64 -O2 -pipe -pipe -fforce-addr -falign-functions=4 -fprefetch-loop-arrays -fomit-frame-pointer"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS=" -Wl,--hash-style=both"

# Skip test
case "${PN}" in
    # These packages often fail src_test
    automake|glibc|e2fsprogs|neon|gettext|tar)
         export SKIP_FUNCTIONS=test
         ;;
    pike|koffice*|monodoc|mono-tools|libevent)
         export SKIP_FUNCTIONS=test
         ;;
esac
